
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/error.css">
    <title>Error 404 - Lost Trip</title>
</head>
<body>
    <div class="container">
        <div class="img-container"></div>
        <h1 class="error-code">404</h1>
        <p class="message"><span class="mayday">MAYDAY!</span> VOCÊ PERDEU O CONTROLE DA PAGINA</p>
        <a href="/home" class="home-button">HOME</a>
    </div>
</body>
</html>